from sl_event import EventTable
from OpenMetaverse import *

events = EventTable([
  #  Owner                   Name                       ArgType
    (AgentManager,          "AgentDataReply",           AgentDataReplyEventArgs),
    (AgentManager,          "AlertMessage",             AlertMessageEventArgs),
    (AgentManager,          "AnimationsChanged",        AnimationsChangedEventArgs),
    (AgentManager,          "AvatarSitResponse",        AvatarSitResponseEventArgs),
    (AgentManager,          "CameraConstraint",         CameraConstraintEventArgs),
    (AgentManager,          "ChatFromSimulator",        ChatEventArgs),
    (AgentManager,          "ChatSessionMemberAdded",   ChatSessionMemberAddedEventArgs),
    (AgentManager,          "ChatSessionMemberLeft",    ChatSessionMemberLeftEventArgs),
    (AgentManager,          "GroupChatJoined",          GroupChatJoinedEventArgs),
    (AgentManager,          "IM",                       InstantMessageEventArgs),
    (AgentManager,          "LoadURL",                  LoadUrlEventArgs),
    (AgentManager,          "MeanCollision",            MeanCollisionEventArgs),
    (AgentManager,          "MoneyBalance",             BalanceEventArgs),
    (AgentManager,          "MoneyBalanceReply",        MoneyBalanceReplyEventArgs),
  # (AgentManager,          "MuteListUpdated",          EventArgs),
    (AgentManager,          "RegionCrossed",            RegionCrossedEventArgs),
    (AgentManager,          "ScriptControlChange",      ScriptControlEventArgs),
    (AgentManager,          "ScriptDialog",             ScriptDialogEventArgs),
    (AgentManager,          "ScriptQuestion",           ScriptQuestionEventArgs),
    (AgentManager,          "ScriptSensorReply",        ScriptSensorReplyEventArgs),
    (AgentManager,          "SetDisplayNameReply",      SetDisplayNameReplyEventArgs),
    (AgentManager,          "TeleportProgress",         TeleportEventArgs),

    (AppearanceManager,     "AgentWearablesReply",      AgentWearablesReplyEventArgs),
    (AppearanceManager,     "AppearanceSet",            AppearanceSetEventArgs),
    (AppearanceManager,     "CachedBakesReply",         AgentCachedBakesReplyEventArgs),
    (AppearanceManager,     "RebakeAvatarRequested",    RebakeAvatarTexturesEventArgs),

    (AssetManager,          "AssetUploaded",            AssetUploadEventArgs),
    (AssetManager,          "ImageReceiveProgress",     ImageReceiveProgressEventArgs),
    (AssetManager,          "InitiateDownload",         InitiateDownloadEventArgs),
    (AssetManager,          "UploadProgress",           AssetUploadEventArgs),
    (AssetManager,          "XferReceived",             XferReceivedEventArgs),

    (AvatarManager,         "AvatarAnimation",          AvatarAnimationEventArgs),
    (AvatarManager,         "AvatarAppearance",         AvatarAppearanceEventArgs),
    (AvatarManager,         "AvatarClassifiedReply",    AvatarClassifiedReplyEventArgs),
    (AvatarManager,         "AvatarGroupsReply",        AvatarGroupsReplyEventArgs),
    (AvatarManager,         "AvatarInterestsReply",     AvatarInterestsReplyEventArgs),
    (AvatarManager,         "AvatarPickerReply",        AvatarPickerReplyEventArgs),
    (AvatarManager,         "AvatarPicksReply",         AvatarPicksReplyEventArgs),
    (AvatarManager,         "AvatarPropertiesReply",    AvatarPropertiesReplyEventArgs),
    (AvatarManager,         "ClassifiedInfoReply",      ClassifiedInfoReplyEventArgs),
    (AvatarManager,         "DisplayNameUpdate",        DisplayNameUpdateEventArgs),
    (AvatarManager,         "PickInfoReply",            PickInfoReplyEventArgs),
    (AvatarManager,         "UUIDNameReply",            UUIDNameReplyEventArgs),
    (AvatarManager,         "ViewerEffect",             ViewerEffectEventArgs),
    (AvatarManager,         "ViewerEffectLookAt",       ViewerEffectLookAtEventArgs),
    (AvatarManager,         "ViewerEffectPointAt",      ViewerEffectPointAtEventArgs),

    (DirectoryManager,      "DirClassifiedsReply",      DirClassifiedsReplyEventArgs),
    (DirectoryManager,      "DirEventsReply",           DirEventsReplyEventArgs),
    (DirectoryManager,      "DirGroupsReply",           DirGroupsReplyEventArgs),
    (DirectoryManager,      "DirLandReply",             DirLandReplyEventArgs),
    (DirectoryManager,      "DirPeopleReply",           DirPeopleReplyEventArgs),
    (DirectoryManager,      "DirPlacesReply",           DirPlacesReplyEventArgs),
    (DirectoryManager,      "EventInfoReply",           EventInfoReplyEventArgs),
    (DirectoryManager,      "PlacesReply",              PlacesReplyEventArgs),

    (EstateTools,           "EstateBansReply",          EstateBansReplyEventArgs),
    (EstateTools,           "EstateCovenantReply",      EstateCovenantReplyEventArgs),
    (EstateTools,           "EstateGroupsReply",        EstateGroupsReplyEventArgs),
    (EstateTools,           "EstateManagersReply",      EstateManagersReplyEventArgs),
    (EstateTools,           "EstateUpdateInfoReply",    EstateUpdateInfoReplyEventArgs),
    (EstateTools,           "EstateUsersReply",         EstateUsersReplyEventArgs),
    (EstateTools,           "TopCollidersReply",        TopCollidersReplyEventArgs),
    (EstateTools,           "TopScriptsReply",          TopScriptsReplyEventArgs),

    (FriendsManager,        "FriendFoundReply",         FriendFoundReplyEventArgs),
    (FriendsManager,        "FriendNames",              FriendNamesEventArgs),
    (FriendsManager,        "FriendOffline",            FriendInfoEventArgs),
    (FriendsManager,        "FriendOnline",             FriendInfoEventArgs),
    (FriendsManager,        "FriendRightsUpdate",       FriendInfoEventArgs),
    (FriendsManager,        "FriendshipOffered",        FriendshipOfferedEventArgs),
    (FriendsManager,        "FriendshipResponse",       FriendshipResponseEventArgs),
    (FriendsManager,        "FriendshipTerminated",     FriendshipTerminatedEventArgs),

    (GridManager,           "CoarseLocationUpdate",     CoarseLocationUpdateEventArgs),
    (GridManager,           "GridItems",                GridItemsEventArgs),
    (GridManager,           "GridLayer",                GridLayerEventArgs),
    (GridManager,           "GridRegion",               GridRegionEventArgs),
    (GridManager,           "RegionHandleReply",        RegionHandleReplyEventArgs),

    (GroupManager,          "CurrentGroups",            CurrentGroupsEventArgs),
    (GroupManager,          "GroupAccountSummaryReply", GroupAccountSummaryReplyEventArgs),
    (GroupManager,          "GroupCreatedReply",        GroupCreatedReplyEventArgs),
    (GroupManager,          "GroupDropped",             GroupDroppedEventArgs),
    (GroupManager,          "GroupInvitation",          GroupInvitationEventArgs),
    (GroupManager,          "GroupJoinedReply",         GroupOperationEventArgs),
    (GroupManager,          "GroupLeaveReply",          GroupOperationEventArgs),
    (GroupManager,          "GroupMemberEjected",       GroupOperationEventArgs),
    (GroupManager,          "GroupMembersReply",        GroupMembersReplyEventArgs),
    (GroupManager,          "GroupNamesReply",          GroupNamesEventArgs),
    (GroupManager,          "GroupNoticesListReply",    GroupNoticesListReplyEventArgs),
    (GroupManager,          "GroupProfile",             GroupProfileEventArgs),
    (GroupManager,          "GroupRoleDataReply",       GroupRolesDataReplyEventArgs),
    (GroupManager,          "GroupRoleMembersReply",    GroupRolesMembersReplyEventArgs),
    (GroupManager,          "GroupTitlesReply",         GroupTitlesReplyEventArgs),

    (InventoryManager,      "FindObjectByPathReply",    FindObjectByPathReplyEventArgs),
    (InventoryManager,      "FolderUpdated",            FolderUpdatedEventArgs),
    (InventoryManager,      "InventoryObjectOffered",   InventoryObjectOfferedEventArgs),
    (InventoryManager,      "ItemReceived",             ItemReceivedEventArgs),
    (InventoryManager,      "SaveAssetToInventory",     SaveAssetToInventoryEventArgs),
    (InventoryManager,      "ScriptRunningReply",       ScriptRunningReplyEventArgs),
    (InventoryManager,      "TaskInventoryReply",       TaskInventoryReplyEventArgs),
    (InventoryManager,      "TaskItemReceived",         TaskItemReceivedEventArgs),

    (NetworkManager,        "Disconnected",             DisconnectedEventArgs),
    (NetworkManager,        "EventQueueRunning",        EventQueueRunningEventArgs),
    (NetworkManager,        "LoggedOut",                LoggedOutEventArgs),
    (NetworkManager,        "LoginProgress",            LoginProgressEventArgs),
    (NetworkManager,        "PacketSent",               PacketSentEventArgs),
    (NetworkManager,        "SimChanged",               SimChangedEventArgs),
    (NetworkManager,        "SimConnected",             SimConnectedEventArgs),
    (NetworkManager,        "SimConnecting",            SimConnectingEventArgs),
    (NetworkManager,        "SimDisconnected",          SimDisconnectedEventArgs),
    
    (ObjectManager,         "AvatarSitChanged",         AvatarSitChangedEventArgs),
    (ObjectManager,         "AvatarUpdate",             AvatarUpdateEventArgs),
    (ObjectManager,         "KillObject",               KillObjectEventArgs),
    (ObjectManager,         "ObjectDataBlockUpdate",    ObjectDataBlockUpdateEventArgs),
    (ObjectManager,         "ObjectProperties",         ObjectPropertiesEventArgs),
    (ObjectManager,         "ObjectPropertiesFamily",   ObjectPropertiesFamilyEventArgs),
    (ObjectManager,         "ObjectPropertiesUpdated",  ObjectPropertiesUpdatedEventArgs),
    (ObjectManager,         "ObjectUpdate",             PrimEventArgs),
    (ObjectManager,         "PayPriceReply",            PayPriceReplyEventArgs),
    (ObjectManager,         "PhysicsProperties",        PhysicsPropertiesEventArgs),
    (ObjectManager,         "TerseObjectUpdate",        TerseObjectUpdateEventArgs),

    (ParcelManager,         "ForceSelectObjectsReply",  ForceSelectObjectsReplyEventArgs),
    (ParcelManager,         "ParcelAccessListReply",    ParcelAccessListReplyEventArgs),
    (ParcelManager,         "ParcelDwellReply",         ParcelDwellReplyEventArgs),
    (ParcelManager,         "ParcelInfoReply",          ParcelInfoReplyEventArgs),
    (ParcelManager,         "ParcelMediaCommand",       ParcelMediaCommandEventArgs),
    (ParcelManager,         "ParcelMediaUpdateReply",   ParcelMediaUpdateReplyEventArgs),
    (ParcelManager,         "ParcelObjectOwnersReply",  ParcelObjectOwnersReplyEventArgs),
    (ParcelManager,         "ParcelProperties",         ParcelPropertiesEventArgs),
    (ParcelManager,         "SimParcelsDownloaded",     SimParcelsDownloadedEventArgs),

    (SoundManager,          "AttachedSound",            AttachedSoundEventArgs),
    (SoundManager,          "AttachedSoundGainChange",  AttachedSoundGainChangeEventArgs),
    (SoundManager,          "PreloadSound",             PreloadSoundEventArgs),
    (SoundManager,          "SoundTrigger",             SoundTriggerEventArgs),

    (TerrainManager,        "LandPatchReceived",        LandPatchReceivedEventArgs),
    ])

responder_for = events.responder_for
